# Generated by Django 4.1.2 on 2022-12-01 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Online')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='First Joined')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionActivity', to='roomApp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionActivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Online',
            },
        ),
        migrations.CreateModel(
            name='UserConnectedChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_online_obj_char', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_value', models.CharField(help_text='Every channel name consists of a specific 74 chars', max_length=74, verbose_name='Channel Name')),
                ('user_online', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionChannels', to='roomApp.useronline')),
            ],
            options={
                'verbose_name_plural': 'User Channel Connections',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roomApp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
