# Generated by Django 4.1.2 on 2022-11-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomApp', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Online')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='First Joined')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionActivity', to='roomApp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionActivity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
