# Generated by Django 4.1.2 on 2022-11-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0004_userconnectedchannels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconnectedchannels',
            options={'verbose_name_plural': 'User Channel Connections'},
        ),
        migrations.AlterModelOptions(
            name='useronline',
            options={'verbose_name_plural': 'Users Online'},
        ),
        migrations.AddField(
            model_name='userconnectedchannels',
            name='user_online_obj_char',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
